### ISSUE TITLE
Clicking page action icon opens all comment pages

### ISSUE THREAD

**Issue by nepsilon** [nepsilon/hn-comments#4]
When several pages, which have been submitted to HN, are open, a single click on the page action icon will open the comment page of each of these pages.

**Comment by angelathewebdev** [comment]
Opening `http://zbowling.github.io/blog/2011/11/25/github/` and a few others will produce the result. In addition, if the post is already deleted on HN, it will also show

**Comment by nepsilon** [comment]
Thanks @angelathewebdev. I'll look into it.
